hospital/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    
    path('admin/', admin.site.urls),
    path('pacientes/' , include('pacientes.urls')),
    path('usuarios/' , include('usuarios.urls')),
    path('articulos/' , include('articulos.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pacientes/urls.py
from django.urls import path
from .views import Lista, Nuevo, Eliminar, Editar, buscar_municipio, Grafica, ListaPacientePdf

app_name = 'pacientes'

urlpatterns = [
    path('lista/', Lista.as_view(), name='lista'),
    
    path('grafica/', Grafica.as_view(), name='pacientes_grafica'),
    path('pdf/',ListaPacientePdf.as_view(), name='pdf'),

    path('nuevo/', Nuevo.as_view(), name='nuevo'),
    path('editar/<int:pk>', Editar.as_view(), name='editar'),
    path('eliminar/<int:pk>', Eliminar.as_view(), name='eliminar'),
    path('busca-municipio/', buscar_municipio, name='buscar_municipio'),

]

pacientes/models.py
from django.db import models


class Estado(models.Model):
    nombre = models.CharField('Nombre del estado',max_length=120)
    def __str__(self):
        return self.nombre
    

class Municipio(models.Model):
    nombre = models.CharField('Nombre del municipio',max_length=120)
    estado = models.ForeignKey(Estado, verbose_name="Estado", on_delete=models.CASCADE)
    def __str__(self):
        return self.nombre


class Paciente(models.Model):
    TIPO_SANGRE =  [
        ('A+', 'A positivo'),
        ('A-', 'A negativo'),
        ('O+', 'O positivo'),
    ]
    nombre = models.CharField(max_length=60)
    primerApellido = models.CharField('Apellido paterno',max_length=60)
    segundoApellido = models.CharField('Apellido materno', max_length=60, null=True, blank=True)
    numero_ss = models.CharField('Número de Seguro Social',max_length=20)
    fecha_nac = models.DateField('Fecha de nacimiento')
    tipo_sangre = models.CharField('Tipo de sangre', max_length=3, choices=TIPO_SANGRE)
    municipio = models.ForeignKey(Municipio, verbose_name='Municipio', on_delete=models.SET_NULL, null=True)
    estado = models.ForeignKey(Estado, verbose_name='Estado', on_delete=models.SET_NULL, null=True)


    def __str__(self):
        return self.nombre + ' ' + self.primerApellido
    

pacientes/forms.py
from .models import Paciente
from django.forms import ModelForm, TextInput, Select, DateInput


class PacienteForm(ModelForm):

    class Meta:
        model = Paciente
        fields = ('nombre','primerApellido','segundoApellido',
            'numero_ss','fecha_nac','tipo_sangre','estado','municipio')

        widgets = {
                'nombre':TextInput(attrs={'class':'form-control'}),
                'primerApellido':TextInput(attrs={'class':'form-control'}),
                'segundoApellido':TextInput(attrs={'class':'form-control'}),
                'numero_ss':TextInput(attrs={'class':'form-control'}),
                'fecha_nac':DateInput(attrs={'class':'form-control'}),
                'tipo_sangre':Select(attrs={'class':'form-control'}),
                'estado':Select(attrs={'class':'form-control'}),
                'municipio':Select(attrs={'class':'form-control'}),
        }

pacientes/views.py
from django.shortcuts import render
from django.views.generic.list import ListView
from django.views.generic import TemplateView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .models import Paciente, Municipio, Estado
from .forms import PacienteForm
from django.urls import reverse_lazy
from django.http import JsonResponse
from django.db.models import Count
from django_weasyprint import WeasyTemplateResponseMixin
from django.conf import settings
from django.contrib.auth.mixins import PermissionRequiredMixin, LoginRequiredMixin, AccessMixin


class Lista(PermissionRequiredMixin, ListView):
    #En este lugar se puede paginar dependiendo de cuantos datos se requieren de la lista y en base a ese numero filtrar.
    #Ejemplo si queremos que apartir de 10 registro cree otra pagina en el atributo paginate_by ponemos 10.
    paginate_by = 10
    model = Paciente
    permission_required = 'usuarios.permiso_administradores'




class Nuevo(PermissionRequiredMixin, CreateView):
    model = Paciente
    form_class = PacienteForm
    success_url = reverse_lazy('pacientes:lista')
    permission_required = 'usuarios.permiso_administradores'

class Editar(PermissionRequiredMixin ,UpdateView):
    model = Paciente
    form_class = PacienteForm
    extra_context = {'editar':True}
    permission_required = 'usuarios.permiso_administradores'
    success_url = reverse_lazy('pacientes:lista')

class Eliminar(PermissionRequiredMixin, DeleteView):
    model = Paciente
    success_url = reverse_lazy('pacientes:lista')
    permission_required = 'usuarios.permiso_administradores'
    
    

def buscar_municipio(request):
    id_estado = request.POST.get('id',None)
    if id_estado:
        municipios = Municipio.objects.filter(estado_id=id_estado)
        data = [{'id':mun.id,'nombre':mun.nombre} for mun in  municipios]
        return JsonResponse(data, safe=False)
    return JsonResponse({'error':'Parámetro inválido'}, safe=False)

class Grafica(TemplateView):
    template_name = 'pacientes/grafica.html'
    def get(self, request, *args, **kwargs):
        paci_municipio = Paciente.objects.all().values('municipio').annotate(cuantos=Count('municipio'))
        municipios = Municipio.objects.all()
        datos = []
        for municipio in municipios:
            cuantos = 0
            for pm in paci_municipio:
                if pm['municipio'] == municipio.id:
                    cuantos = pm['cuantos']
                    break  
            datos.append({'name':municipio.nombre, 'data':[cuantos]})
        self.extra_context = {'datos':datos}
        context = self.get_context_data(**kwargs)
        return self.render_to_response(context)


class VistaPdf(ListView):
    model = Paciente
    template_name = 'pacientes/pacientes_pdf.html'

class ListaPacientePdf(WeasyTemplateResponseMixin, VistaPdf):
    passpdf_stylesheets = [
        settings.STATICFILES_DIRS[0] + 'css/boostrap.min.css',
    ]
    pdf_attachment = False
    pdf_filename = 'paciente.pdf'
    

pacientes/templates/pacientes/grafica.html
{% extends 'base.html' %}

{% block titulo %}
    GRAFICA
{% endblock titulo %}

{% block contenido %}

    <div id="grafica" style="min-width: 310px; height: 400 px; margin: 0 auto;"></div>
    <script src="https://code.highcharts.com/highcharts.src.js"></script>
    <script src="https://code.highcharts.com/modules/exporting.js"></script>
    <script src="https://code.highcharts.com/modules/exporting_data.js"></script>
    
    <script>
        Highcharts.chart('grafica',{
            lang:{
                downloadCSV: 'Descarga CSV',
                downloadJPEG: 'Descarga imagen JPEG',
                downloadPDF: 'Descarga PDF',
                downloadPNG: 'Descarga imagen PNG',
                downloadSVG: 'Descarga en imagen en vectores',
                viewFullscreen: 'Ver en pantalla completa',
                printChart: 'Imprimir grafica',
            },
            chart:{
                type: 'column',
            },
            title:{
                text: 'Grafica de pacientes',
            },
            subtitle:{
                text: 'Cuantos pacientes por municipio',
            },
            xAxis:{
                categorias:['Municipios'],
            },
            yAxis:{
                min: 0,
                title: {
                    text: 'Cantidad de pacientes'
                },
            },
            plotOptions:{
                column:{
                    pointPadding: 0.2,
                    borderWidth: 0,
                },
            },
            series: {{datos | safe}}
        });
        
    </script>

{% endblock contenido %}
    
    

pacientes/templates/pacientes/paciente_confirm_delete.html
{% extends 'base.html' %}
{% block titulo %}
    Eliminar paciente
{% endblock titulo %}

{% block contenido %}

<form method="post">
    {% csrf_token %}
    <p>Quieres eliminar el paciente "{{ object }}"?</p>
    <input class="btn btn-danger" type="submit" value="Sí, si quiero">
    <a href="{% url 'pacientes:lista' %}" class="btn btn-secondary" >Mejor no</a>
</form>

{% endblock contenido %}

pacientes/templates/pacientes/paciente_form.html
{% extends 'base.html' %}

{% block titulo %}
    Agrega paciente
{% endblock titulo %}

{% block contenido %}
<div class="row">
    <div class="col-md-2"></div> 
    <div class="col-md-8">
        <div class="card card-primary">
            <div class="card-header">
                <h3 class="card-title">
                    {% if editar %}
                        Modificar paciente
                    {% else %}
                        Nuevo paciente
                    {% endif %}
                </h3>
            </div>
                <form method="post">
                    <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p }}
                    </div>
                    <div class="card-footer">
                        <input type="submit" class="btn btn-success" value="{% if editar %}Guardar cambios{% else %}Agregar{% endif %}">
                    </div>
                </form>
            </div>
        </div>
    </div> 
    <div class="col-md-2"></div> 

    {% endblock contenido %}
    
    

pacientes/templates/pacientes/paciente_list.html
{% extends 'base.html' %}

{% block titulo %}Lista de pacientes{% endblock titulo %}
    
{% block contenido %}
<h1>Lista de pacientes</h1>
<table class="table table-bordered">
    <thead>
        <tr>
            <th>Nombre</th>
            <th>Apellido paterno</th>
            <th>Apellido materno</th>
            <th>Fecha de nacimiento</th>
            <th>No. Seguro social</th>
            <th>Tipo de sangre</th>
            <th>Opciones</th>
        </tr>
    </thead>
    <tbody>
        {% for paciente in object_list %}
        <tr>
            <td>{{paciente.nombre}}</td>
            <td>{{paciente.primerApellido}}</td>
            <td>{{paciente.segundoApellido}}</td>
            <td>{{paciente.fecha_nac}}</td>
            <td>{{paciente.numero_ss}}</td>
            <td>{{paciente.tipo_sangre}}</td>
            <td>
                <a title="Actualiza paciente" class="btn btn-warning" href="{% url 'pacientes:editar' paciente.id %}">
                    <i class="far fa-edit"></i>
                </a>
                <a title="Elimina paciente" class="btn btn-danger" href="{% url 'pacientes:eliminar' paciente.id %}">
                    <i class="far fa-trash-alt"></i>
                </a>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>


<nav aria-label="...">
    <ul class="pagination">
        
        {% if page_obj.has_previous %}
            <li>
                <a class="page-link" href="?page=1">Firts</a>
            </li>
            <li>
                <a class="page-link" href="?page={{ page_obj.previous_page_number }}" >Previous</a>
            </li>
            <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">{{page_obj.previous_page_number}}</a></li>
        {% endif %}

      <li class="page-item active">
        <a class="page-link" href="#"> {{ page_obj.number }} <span class="sr-only">(current)</span></a>
      </li>
      
        {% if page_obj.has_next %}
            <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a></li>
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a>
            </li>
            <li>
                <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
            </li>
        {% endif %}
    </ul>
  </nav>

{% endblock contenido %}
    

pacientes/templates/pacientes/pacientes_pdf.html
{% extends 'base.html' %}

{% block titulo %}Lista de pacientes{% endblock titulo %}
    
{% block contenido %}
<h1>Lista de pacientes</h1>
<table class="table table-bordered">
    <thead>
        <tr>
            <th>Nombre</th>
            <th>Apellido paterno</th>
            <th>Apellido materno</th>
            <th>Fecha de nacimiento</th>
            <th>No. Seguro social</th>
            <th>Tipo de sangre</th>
        </tr>
    </thead>
    <tbody>
        {% for paciente in object_list %}
        <tr>
            <td>{{paciente.nombre}}</td>
            <td>{{paciente.primerApellido}}</td>
            <td>{{paciente.segundoApellido}}</td>
            <td>{{paciente.fecha_nac}}</td>
            <td>{{paciente.numero_ss}}</td>
            <td>{{paciente.tipo_sangre}}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock contenido %}