articulos/urls.py
from django.urls import path
from .views import Lista, comprar, cancelarCompra, Carrito, confirmarCompra, eliminarArt

app_name = 'articulos'

urlpatterns = [
    path('lista/', Lista.as_view(), name='lista'),

    path('comprar/<int:pk>', comprar, name='comprar'),
    
    path('eliminar/<int:pk>', eliminarArt, name='eliminar'),

    path('cancelarCompra/', cancelarCompra, name='cancelarCompra'),
    
    path('confirmarCompra/', confirmarCompra, name='confirmarCompra'),
    
    path('carrito/', Carrito.as_view(), name='carrito'),
    

]

hospital/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    
    path('admin/', admin.site.urls),
    path('pacientes/' , include('pacientes.urls')),
    path('usuarios/' , include('usuarios.urls')),
    path('articulos/' , include('articulos.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

articulos/models.py
from django.db import models


class Articulo(models.Model):

    clave = models.CharField("Clave", max_length=30)
    nombre = models.CharField("Artícuclo", max_length=150)
    descripcion = models.CharField("Descripción", max_length=300, blank=True, null=True)
    imagen = models.ImageField("Imagen", upload_to="articulos")
    precio = models.DecimalField("Precio", max_digits=8, decimal_places=2)
    stock = models.IntegerField("Unidades")
    categoria = models.ForeignKey("articulos.Categoria", verbose_name="Categoría", on_delete=models.DO_NOTHING)

    def __str__(self):
        return self.nombre


class Categoria(models.Model):
    nombre = models.CharField("Categoria", max_length=150)

    def __str__(self):
        return self.nombre


class Venta(models.Model):
	fecha = models.DateField(auto_now_add=True)
	detalle_venta = models.ForeignKey('articulos.DetalleVenta',verbose_name='DetalleVenta',on_delete=models.CASCADE, null=True)

	def __str__(self):
		return str(self.fecha)

class DetalleVenta(models.Model):
	cantidad = models.IntegerField('Articulos vendidos', null=True)
	total = models.DecimalField('Total Venta', max_digits=10, decimal_places=2, null=True)

articulos/forms.py
from django import forms

class QuantityForm(forms.Form):
	cantidad = forms.IntegerField()

articulos/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic.list import ListView
from django.views.generic import TemplateView, DeleteView
from django.views.generic.edit import FormMixin
from .models import Articulo, Venta, DetalleVenta
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from .forms import QuantityForm

class Lista(LoginRequiredMixin, ListView):
    template_name = 'articuo_list.html'
    model = Articulo
    form_class = QuantityForm
    paginate_by = 5


def eliminarArt(request, pk):
    primarykey = int(pk)
    obj = get_object_or_404(Articulo, id=primarykey)
    obj.delete()
    return redirect('articulos:lista')



def comprar(request, pk):
    articulo = get_object_or_404(Articulo, pk=pk)
    if articulo.stock > 0: 
        cantidad_articulos = int(request.POST.get('cantidad_articulos'))
        
        if cantidad_articulos <= articulo.stock and cantidad_articulos > -1:
            articulo.stock = articulo.stock - cantidad_articulos
            articulo.save()
            id = str(pk)
            request.session['total'] = request.session['total'] + (float(articulo.precio)*cantidad_articulos)
            request.session['cuantos'] = request.session['cuantos'] + cantidad_articulos
            if id in request.session['articulos']:
                request.session['articulos'][id]['cantidad'] = request.session['articulos'][id]['cantidad'] + cantidad_articulos
            else:
                request.session['articulos'][id] = {'precio':float(articulo.precio),'cantidad':cantidad_articulos}
        
    return redirect('articulos:lista')


class Carrito(LoginRequiredMixin, ListView):
    model = Articulo
    extra_context = {'carrito':True}

    def get_queryset(self):
        ids = list(self.request.session['articulos'])
        all_articles = Articulo.objects.filter(id__in = ids)
        return all_articles

def cancelarCompra(request):
    keys = list(request.session['articulos'].keys())
    for pk in keys:
        articulo_temp = get_object_or_404(Articulo, pk=pk)
        id = str(pk)
        articulo_temp.stock += request.session['articulos'][id]['cantidad']
        articulo_temp.save()
    request.session['cuantos'] = 0
    request.session['total'] = 0.0
    request.session['articulos'] = {}
    return redirect('articulos:lista')

def confirmarCompra(request):
    cantidad = request.session['cuantos']
    total = request.session['total']
    detalle_venta = DetalleVenta(cantidad=cantidad, total=total)
    detalle_venta.save()
    venta = Venta(detalle_venta=detalle_venta)
    venta.save()
    request.session['cuantos'] = 0
    request.session['total'] = 0.0
    request.session['articulos'] = {}
    return redirect('articulos:lista')

articulos/templates/articulos/articulo_list.html
{% extends 'base.html' %}

{% block titulo %}
    {% if carrito%}
        Articulos en el Carrito
    {% else %}
        Lista de Articulos
    {% endif %}
{% endblock titulo %}
    
{% block contenido %}

{% if carrito %}
    <h1>Artículos en el carrito</h1>
    <table class="table table-bordered">
    <thead>
        <tr>
            <th>Clave</th>
            <th>Artículo</th>
            <th>Descripción</th>
            <th>Imagen</th>
            <th>Precio</th>
            <th>Cantidad</th>
        </tr>
    </thead>
    <tbody>
        {% for articulo in object_list %}
        <tr>
            <td>{{articulo.clave}}</td>
            <td>{{articulo.nombre}}</td>
            <td>{{articulo.descripcion}}</td>
            <td><img src="{{MEDIA_URL}}/{{articulo.imagen}}" width="100px" height="100px"></td>
            <td>${{articulo.precio|floatformat:2}}</td>
            <td>{{request.session.articulos|dict_key:articulo.id}}</td>
        </tr>
        {% endfor %}
    </tbody>
    </table>
    <h3 style="text-align: right" >Cantidad de Articulos: {{request.session.cuantos}}</h3>
    <h3 style="text-align: right" >Total: {{request.session.total|floatformat:2}}</h3>
    <div class="btn-group" style="float: right;">
    <a title="Confirmar compra" class="button type1" style="color: green;"  href="{% url 'articulos:confirmarCompra' %}">
        <i class="fas fa-money-bill-wave"></i>
    </a>
    <a title="Cancelar compra" class="button type1" style="color: red;" style="width:100px;margin:2px" href="{% url 'articulos:cancelarCompra' %}">
        <i class="fas fa-heart-broken"></i>
    </a>
    </div>


{% else %}

    <h1>Lista de Artículos</h1>
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Clave</th>
                <th>Artículo</th>
                <th>Precio</th>
                <th>Existencia</th>
                <th>Cantidad</th>
                <th>Agregar al carro</th>
                {% if perms.usuarios.permiso_administradores %}
                    <th>Eliminar articulo</th>
                {% endif %}
            </tr>
        </thead>
        <tbody>
            {% for articulo in object_list %}
            <tr>
                <td>{{articulo.clave}}</td>
                <td>{{articulo.nombre}}</td>
                <td>${{articulo.precio}}</td>
                <td>{{articulo.stock}}</td>
                <form method="post" action="{% url 'articulos:comprar' articulo.id %}">
                    {% csrf_token %}
                    <td>
                        <input type="number" name="cantidad_articulos" style="width:50px" min="0" max="{{ articulo.stock }}" value="0">
                    </td>
                    <td>
                        {% if articulo.stock > 0 %}

                            <button type="submit" title="Agregar a carrito" class="boton"><i class="fas fa-cart-plus"></i></button>
                            
                        {% else %}
                        
                
                            <a href="" class="btn btn-warning" title="sin stock">
                                <i class="fas fa-frown"></i>
                            </a>
                        {% endif %}
    
                    </td>

                    {% if perms.usuarios.permiso_administradores %}
                    
                        <td>
                            <a class="boton" style="color: red;" href="javascript:eliminarModal( '{% url 'articulos:eliminar' articulo.id %}' )">
                                <i class="fas fa-trash"></i>
                            </a>
                        </td>
                        
                    {% endif %}

                </form>
            </tr>
            {% endfor %}


        </tbody>
    </table>

{% endif %}

            <!--modal-->
            <button hidden id="btnModal" type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
                Launch demo modal
            </button>

            <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog" role="document">
                  <div class="modal-content">
                    <div class="modal-header">
                      <h5 class="modal-title" id="exampleModalLabel">Elimina articulo</h5>
                      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                      </button>
                    </div>
                    <div class="modal-body">
                      ¿Estas seguro de eliminar el articulo? 
                    </div>
                    <div class="modal-footer">
                      <button type="button" class="btn btn-secondary" data-dismiss="modal"><a class="btn btn-secondary" href=""> Cancelar</a></button>
                      <button type="button" class="btn btn-danger"><a class="btn btn-danger" id="confirmaEliminacion" href=""> Eliminar</a></button>
                    </div>
                  </div>
                </div>
              </div>
              <!--modal-->


<nav aria-label="...">
    <ul class="pagination">
        
        {% if page_obj.has_previous %}
            <li>
                <a class="page-link" href="?page=1">Firts</a>
            </li>
            <li>
                <a class="page-link" href="?page={{ page_obj.previous_page_number }}" >Previous</a>
            </li>
            <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">{{page_obj.previous_page_number}}</a></li>
        {% endif %}

      <li class="page-item active">
        <a class="page-link" href="#"> {{ page_obj.number }} <span class="sr-only">(current)</span></a>
      </li>
      
        {% if page_obj.has_next %}
            <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a></li>
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a>
            </li>
            <li>
                <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
            </li>
        {% endif %}
    </ul>
  </nav>

  <style>
    .boton {
        text-decoration:none;
        font-weight: 60;
        font-size: 20px;
        color:#333333;
        padding-top:5px;
        padding-bottom:5px;
        padding-left:10px;
        padding-right:10px;
        background-color:rgba(60, 255, 0, 0.39);
        border-color: black;
        border-width: 3px;
        border-style: solid;
        border-radius:35px;
 }
</style>

  <script>
    function eliminarModal(url) {
        document.querySelector("#confirmaEliminacion").setAttribute('href',url);
        document.querySelector("#btnModal").click()
    }
  </script>

<style>
    @import url("https://fonts.googleapis.com/css?family=Raleway");
* {
  box-sizing: border-box;
}
.copyright {
  position: absolute;
  bottom: 0;
}
.copyright a {
  text-decoration: none;
  color: #16a085;
}
.copyright a:hover {
  text-decoration: underline;
}

.button {
  position: relative;
  padding: 1em 1.5em;
  border: none;
  background-color: transparent;
  cursor: pointer;
  outline: none;
  font-size: 16px;
  margin: 1em 0.8em;
}
.button.type1 {
  color: #566473;
}
.button.type1.type1::after, .button.type1.type1::before {
  content: "";
  display: block;
  position: absolute;
  width: 20%;
  height: 20%;
  border: 2px solid;
  transition: all 0.6s ease;
  border-radius: 2px;
}
.button.type1.type1::after {
  bottom: 0;
  right: 0;
  border-top-color: transparent;
  border-left-color: transparent;
  border-bottom-color: #566473;
  border-right-color: #566473;
}
.button.type1.type1::before {
  top: 0;
  left: 0;
  border-bottom-color: transparent;
  border-right-color: transparent;
  border-top-color: #566473;
  border-left-color: #566473;
}
.button.type1.type1:hover:after, .button.type1.type1:hover:before {
  width: 100%;
  height: 100%;
}
</style>

{% endblock contenido %}
    